// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkT5FyjxX9crfOHkebOXph5vbn44oEu_o',
    appId: '1:41889985478:web:5d675a1ca1d3e8cb6fb8c7',
    messagingSenderId: '41889985478',
    projectId: 'gestion-stages-notifs',
    authDomain: 'gestion-stages-notifs.firebaseapp.com',
    storageBucket: 'gestion-stages-notifs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTr-q1GIvFJC0r2WfAh1XFZYChueqlVIo',
    appId: '1:41889985478:android:c6e05238e07000416fb8c7',
    messagingSenderId: '41889985478',
    projectId: 'gestion-stages-notifs',
    storageBucket: 'gestion-stages-notifs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_TPt4ILbjYepwMwiCrl6qQ9nrV6LJzUw',
    appId: '1:41889985478:ios:96986744c25d2fbf6fb8c7',
    messagingSenderId: '41889985478',
    projectId: 'gestion-stages-notifs',
    storageBucket: 'gestion-stages-notifs.firebasestorage.app',
    iosBundleId: 'com.example.pfeproject',
  );
}
